[package]
name = "hackaton_railify"
version = "0.1.0"
edition = "2021"

[dependencies]
draw = { path = "draw" }
image = "0.25.4"
imageproc = "0.25.0"
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["derive"] }
pdf = "0.9.0"
pdfium-render = "0.8.25"
nannou = "0.19.0"
svg = "0.18"
