[package]
name = "hackaton_railify"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
clap = { version = "4.5.20", features = ["derive"] }
image = "0.25.4"
pdf = "0.9.0"
pdfium-render = "0.8.25"
